{
 "title": "Sales dashboard",
 "time": { "from": "now-8d", "to": "now" },
 "panels": [
  {
   "title": "Distribution of Revenue by Product",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    product_name,\r\n    SUM(revenue) AS value\r\nFROM\r\n    sales_data\r\nGROUP BY\r\n    product_name\r\n"
    }
   ]
  },
  {
   "title": "Units sold by product",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    product_name,\r\n    SUM(units_sold) AS value\r\nFROM\r\n    sales_data\r\nGROUP BY\r\n    product_name\r\n"
    }
   ]
  },
  {
   "title": "Sales Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    sale_date AS time,\r\n    SUM(units_sold) AS total_sales\r\nFROM\r\n    sales_data\r\nGROUP BY\r\n    sale_date\r\n"
    }
   ]
  },
  {
   "title": "Total available items",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "   select product_name,\r\n    MAX(stock_available) AS value\r\nFROM\r\n    sales_data\r\nGROUP BY\r\n    product_name"
    }
   ]
  }
 ]
}